// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOAmIrb8OUfS9UiuIw6qRA5LsHlNW4WdA',
    appId: '1:103403575515:web:45f84ab7e28820114e94fe',
    messagingSenderId: '103403575515',
    projectId: 'mapdialog-1aa4e',
    authDomain: 'mapdialog-1aa4e.firebaseapp.com',
    storageBucket: 'mapdialog-1aa4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQ95MUBLH3cBu-_4ywho8ReLdBylZ2-A',
    appId: '1:103403575515:android:b43307dddfe482784e94fe',
    messagingSenderId: '103403575515',
    projectId: 'mapdialog-1aa4e',
    storageBucket: 'mapdialog-1aa4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpF-r2kHLcTy2sqmO8lm7w8JItxEKcm1U',
    appId: '1:103403575515:ios:d278a56b281d8f874e94fe',
    messagingSenderId: '103403575515',
    projectId: 'mapdialog-1aa4e',
    storageBucket: 'mapdialog-1aa4e.appspot.com',
    iosBundleId: 'com.example.mapDialogApp',
  );
}
